## application's name
TARGET=controller

## folders where C files are located
USR_PATH=.

## link options
USR_LIBS=

## user files
USR_CFILES=\
   my_glue.c \
   Controller.c \

## generic makefile for OSEK (requires MDL2LUS2OSEK variable)
include $(MDL2LUS2OSEK)/generic.mak
